#pragma once

#undef TAPPING_TOGGLE
#undef TAPPING_TERM
// #undef IGNORE_MOD_TAP_INTERRUPT
#undef ONESHOT_TAP_TOGGLE

#define TAPPING_TOGGLE  2
#define TAPPING_TERM    1
// #define IGNORE_MOD_TAP_INTERRUPT
#define ONESHOT_TAP_TOGGLE 2

#undef DEBOUNCE
#define DEBOUNCE 10
 

#undef RETRO_TAPPING
#define RETRO_TAPPING

// #undef FORCE_NKRO
// #define FORCE_NKRO
#undef MOUSEKEY_DELAY
#undef MOUSEKEY_INTERVAL
#undef MOUSEKEY_MAX_SPEED
#undef MOUSEKEY_TIME_TO_MAX
#undef MOUSEKEY_WHEEL_MAX_SPEED
#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#undef MOUSEKEY_WHEEL_DELTA

#define MOUSEKEY_DELAY             0
#define MOUSEKEY_INTERVAL          30
#define MOUSEKEY_MAX_SPEED         5
#define MOUSEKEY_TIME_TO_MAX       40
#define MOUSEKEY_WHEEL_MAX_SPEED   1
#define MOUSEKEY_WHEEL_TIME_TO_MAX 255
#define MOUSEKEY_WHEEL_DELTA 1
